name: coucou

on:
  push:
    branches: [ main ]
    
jobs:
  mon-coucou:
    runs-on: [self-hosted,windows]
    defaults:
      run:
        shell: cmd
    steps:
      - name: Coucou
        run: echo Bonjour Windows depuis cmd !